### ISSUE TITLE
xsh hangs on open on OSX (bash and zsh)

### ISSUE THREAD

**Issue by yonkeltron** [trogdoro/xiki#127]
Hello.

I have tried to install xiki/xsh as described in the README but have met with the following odd problems. First, when I try to launch xsh -- in any form, whether from `bin/xsh` or by adding `~/xiki/bin` to my PATH -- it hangs and accepts no input. I get this from the log in `/tmp`:

```
/Users/yonkeltron/xiki/lib/xiki/core/bookmarks.rb:156: warning: duplicated key at line 160 ignored: "xiki"
/Users/yonkeltron/xiki/lib/xiki/core/bookmarks.rb:157: warning: duplicated key at line 161 ignored: "source"
/Users/yonkeltron/xiki/lib/xiki/core/bookmarks.rb:158: warning: duplicated key at line 162 ignored: "s"
/Users/yonkeltron/xiki/lib/xiki.rb:476:in `yaml_setup': uninitialized constant Psych::ENGINE (NameError)
	from /Users/yonkeltron/xiki/lib/xiki.rb:276:in `init'
	from /Users/yonkeltron/xiki/misc/emacs/el4r/init.rb:4:in `instance_eval_invoker'
	from /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance:614:in `instance_eval'
	from /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance:614:in `instance_eval_invoker'
	from /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance:1024:in `block in <main>'
	from /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance:1014:in `fork'
	from /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance:1014:in `<main>'
```

Trying xsh in different ways (`--help` works fine) yields a bunch of wonderful orphan processes:

```
28183   ??  Ss     0:00.04 /Users/yonkeltron/.rvm/rubies/ruby-2.2.0/bin/ruby /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance forker
28422   ??  Ss     0:00.04 /Users/yonkeltron/.rvm/rubies/ruby-2.2.0/bin/ruby /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance forker
28438   ??  Ss     0:00.04 /Users/yonkeltron/.rvm/rubies/ruby-2.2.0/bin/ruby /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance forker
28528   ??  Ss     0:00.03 /Users/yonkeltron/.rvm/rubies/ruby-2.2.0/bin/ruby /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance forker
28741   ??  Ss     0:00.04 /Users/yonkeltron/.rvm/rubies/ruby-2.2.0/bin/ruby /Users/yonkeltron/xiki/misc/emacs/el4r/el4r-instance forker
```

About my environment OSX Mavericks 10.9:

```
$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
$ uname -a
Darwin WLDMB0074.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
```

**Comment by trogdoro** [comment]
This should be fixed now. Please try again!

**Comment by yonkeltron** [comment]
Can confirm. Thanks!
