### ISSUE TITLE
Startup fails with Ruby error

### ISSUE THREAD

**Issue by a-m-s** [trogdoro/xiki#129]
Here's the error log:

```
12:54:07:247  Booted.
12:54:07:247  Starting, waiting for expression.
/home/ams-unencrypted/xiki/xiki/lib/xiki/core/bookmarks.rb:156: warning: duplicated key at line 160 ignored: "xiki"
/home/ams-unencrypted/xiki/xiki/lib/xiki/core/bookmarks.rb:157: warning: duplicated key at line 161 ignored: "source"
/home/ams-unencrypted/xiki/xiki/lib/xiki/core/bookmarks.rb:158: warning: duplicated key at line 162 ignored: "s"
/tmp/el4r:1: warning: encountered \r in middle of line, treated as a mere space
12:54:07:431  Error: uninitialized constant Psych::ENGINE (NameError)
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:742:in `instance_eval'
  from /home/ams-unencrypted/xiki/xiki/lib/xiki.rb:276:in `init'
  from (eval):4:in `el4r_boot'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:742:in `instance_eval'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:742:in `el4r_boot'
  from /tmp/el4r:1:in `el4r_ruby_eval'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:867:in `instance_eval'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:867:in `el4r_ruby_eval'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:811:in `el4r_get'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:787:in `block in el4r_wait_expr'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:855:in `el4r_with_call'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:784:in `el4r_wait_expr'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:767:in `block in el4r_wait_expr_loop'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:765:in `catch'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:765:in `el4r_wait_expr_loop'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:555:in `main'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:1136:in `<main>'
12:55:02:218  SIGHUP (SignalException)
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:767:in `eof?'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:767:in `block in el4r_wait_expr_loop'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:765:in `catch'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:765:in `el4r_wait_expr_loop'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:555:in `main'
  from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:1136:in `<main>'
12:55:02:218  Exiting.
```

I'm on Arch Linux, with Ruby and Emacs installed.

```
> ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
> emacs --version
GNU Emacs 24.4.1
Copyright (C) 2014 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
> gem list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
test-unit (3.0.8)
> gem check
Checking gems...
```

I'm afraid I don't know enough about Ruby to give further details.

**Comment by iachettifederico** [comment]
I had the same error. I fixed it by using Ruby 2.0 instead of 2.1

$ rvm install 2.1
$ rvm use 2.1
$ xiki -i

You can leave 2.1 as the default ruby by running

$ rvm use 2.1 --default

Federico Martín Iachetti
http://federico.iachetti.com.ar/

On Thu, Feb 12, 2015 at 10:04 AM, a-m-s <notifications@github.com> wrote:

Here's the error log:
>
> 12:54:07:247  Booted.
> 12:54:07:247  Starting, waiting for expression.
> /home/ams-unencrypted/xiki/xiki/lib/xiki/core/bookmarks.rb:156: warning: duplicated key at line 160 ignored: "xiki"
> /home/ams-unencrypted/xiki/xiki/lib/xiki/core/bookmarks.rb:157: warning: duplicated key at line 161 ignored: "source"
> /home/ams-unencrypted/xiki/xiki/lib/xiki/core/bookmarks.rb:158: warning: duplicated key at line 162 ignored: "s"
> /tmp/el4r:1: warning: encountered \r in middle of line, treated as a mere space
> 12:54:07:431  Error: uninitialized constant Psych::ENGINE (NameError)
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:742:in `instance_eval'
>   from /home/ams-unencrypted/xiki/xiki/lib/xiki.rb:276:in `init'
>   from (eval):4:in `el4r_boot'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:742:in `instance_eval'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:742:in `el4r_boot'
>   from /tmp/el4r:1:in `el4r_ruby_eval'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:867:in `instance_eval'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:867:in `el4r_ruby_eval'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:811:in `el4r_get'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:787:in `block in el4r_wait_expr'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:855:in `el4r_with_call'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:784:in `el4r_wait_expr'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:767:in `block in el4r_wait_expr_loop'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:765:in `catch'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:765:in `el4r_wait_expr_loop'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:555:in `main'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:1136:in `<main>'
> 12:55:02:218  SIGHUP (SignalException)
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:767:in `eof?'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:767:in `block in el4r_wait_expr_loop'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:765:in `catch'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:765:in `el4r_wait_expr_loop'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:555:in `main'
>   from /home/ams-unencrypted/xiki/xiki/misc/emacs/el4r/el4r-instance:1136:in `<main>'
> 12:55:02:218  Exiting.
>
> I'm on Arch Linux, with Ruby and Emacs installed.
>
> > ruby --version
> ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
> > emacs --version
> GNU Emacs 24.4.1
> Copyright (C) 2014 Free Software Foundation, Inc.
> GNU Emacs comes with ABSOLUTELY NO WARRANTY.
> You may redistribute copies of Emacs
> under the terms of the GNU General Public License.
> For more information about these matters, see the file named COPYING.
> > gem list
>
> *** LOCAL GEMS ***
>
> bigdecimal (1.2.6)
> io-console (0.4.3)
> json (1.8.1)
> minitest (5.4.3)
> power_assert (0.2.2)
> psych (2.0.8)
> rake (10.4.2)
> rdoc (4.2.0)
> test-unit (3.0.8)
> > gem check
> Checking gems...
>
> I'm afraid I don't know enough about Ruby to give further details.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trogdoro/xiki/issues/129>.
>
​

**Comment by aissat** [comment]
same pbm
02:30:00:069  Error: uninitialized constant Psych::ENGINE (NameError)                                                               
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:742:in `instance_eval'                                                         
  from /home/$home/xiki/lib/xiki.rb:276:in `init'                                                                                    
  from (eval):4:in `el4r_boot'                                                                                                      
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:742:in `instance_eval'                                                         
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:742:in `el4r_boot'                                                             
  from /tmp/el4r:1:in `el4r_ruby_eval'                                                                                              
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:867:in `instance_eval'                                                         
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:867:in `el4r_ruby_eval'                                                        
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:811:in `el4r_get'                                                              
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:787:in `block in el4r_wait_expr'                                               
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:855:in `el4r_with_call'                                                        
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:784:in `el4r_wait_expr'                                                        
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:767:in `block in el4r_wait_expr_loop'                                          
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:765:in `catch'                                                                 
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:765:in `el4r_wait_expr_loop'                                                   
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:555:in `main'                                                                  
  from /home/$home/xiki/misc/emacs/el4r/el4r-instance:1136:in `<main>'

**Comment by trogdoro** [comment]
It should be fixed now. Grab the latest and try again!

--Craig

**Comment by ams-cs** [comment]
Confirmed, it works now. Thanks.

**Comment by a-m-s** [comment]
Confirmed, it works now. Thanks.

**Comment by iachettifederico** [comment]
It works when I use xsh -i but not when using just xsh. If I don't pass -i
I just see an empty buffer

Federico Martín Iachetti
http://federico.iachetti.com.ar/

**Comment by a-m-s** [comment]
I found "killall -9 emacs" cleared that. Apparently the background daemon can get into a bad state.

**Comment by trogdoro** [comment]
Yeah, try killing the forker process ("$ ps aux|grep forker"). It's likely hanging around and is using the old code, since xsh -i is working. Then please report back so I can close this issue!

**Comment by trogdoro** [comment]
This error is probably long-fixed. Try installing xiki using the one-line installer on xiki.com (or the github xiki readme).

You'll probably want to use ruby 2.0 or 2.1

**Comment by trogdoro** [comment]
I'll close this issue if no one says otherwise.
