### ISSUE TITLE
Xiki::Menu::Mysql.create "table"

### ISSUE THREAD

**Issue by aissat** [trogdoro/xiki#131]
mysql/
  =tables/
  =dbs/
    + gitlabhq_production/
    - hello/
      > No tables exist.  Create one? 
      =mysql/setup/table/create/hello/tab1/
        | id int not null auto_increment primary key,
        | name VARCHAR(25),
        | details text,
        | datestamp DATE,
        | timestamp TIME,
          tmp/
            - tried to run:
              : Xiki::Menu::Mysql.create "table", "hello", "tab1", "id int not null auto_increment primarykey,
              : name VARCHAR(25),  text,
              : datestamp DATE,
              : timestamp TIME,"
            - error: wrong number of arguments (5 for 1..4)
            - backtrace:
              =/xiki/lib/xiki/core/invoker.rb:166:in `call'
              =/xiki/lib/xiki/core/invoker.rb:166:in `block in invoke'
              =/xiki/lib/xiki/core/code.rb:292:in `module_eval'
              =/xiki/lib/xiki/core/code.rb:292:in `eval_inner'
              =/xiki/lib/xiki/core/code.rb:260:in `eval'
              =/xiki/lib/xiki/core/invoker.rb:167:in `invoke'
              =/xiki/lib/xiki/handlers/ruby_handler.rb:25:in `handle_class'
              =/xiki/lib/xiki/handlers/ruby_handler.rb:17:in `handl

**Comment by trogdoro** [comment]
I need to make the db settings more configurable, and walk people through populating the settings if they haven't yet. I'll treat this issue as a placeholder for that.
