### ISSUE TITLE
That's not good behavior $ xiki --help

### ISSUE THREAD

**Issue by dslackw** [trogdoro/xiki#170]
When I run ```xiki --help``` or like this ```xiki -``` I get this error:
```
undefined method `gsub' for nil:NilClass
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/lib/xiki/menu.rb:439:in `call'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/lib/xiki/menu.rb:435:in `[]'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/etc/command/xiki_process.rb:27:in `block (3 levels) in run'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/etc/command/xiki_process.rb:16:in `loop'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/etc/command/xiki_process.rb:16:in `block (2 levels) in run'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/etc/command/xiki_process.rb:15:in `open'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/etc/command/xiki_process.rb:15:in `block in run'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/etc/command/xiki_process.rb:13:in `open'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/etc/command/xiki_process.rb:13:in `run'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/etc/command/xiki_process.rb:48:in `<top (required)>'
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.5/lib/daemons/application.rb:223:in `load'
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.5/lib/daemons/application.rb:223:in `start_load'
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.5/lib/daemons/application.rb:302:in `start'
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.5/lib/daemons/controller.rb:56:in `run'
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.5/lib/daemons.rb:148:in `block in run'
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.5/lib/daemons/cmdline.rb:92:in `call'
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.5/lib/daemons/cmdline.rb:92:in `catch_exceptions'
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.5/lib/daemons.rb:147:in `run'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/etc/command/xiki_command.rb:87:in `run'
/usr/lib64/ruby/gems/2.2.0/gems/xiki-0.6.5/bin/xiki:30:in `<top (required)>'
/usr/bin/xiki:23:in `load'
/usr/bin/xiki:23:in `<main>'
```

**Comment by trogdoro** [comment]
You want the "xsh" command (XikiShell), not the "xiki" command.

The xiki command is temporarily disabled (I should clean up that error).

--Craig

**Comment by dslackw** [comment]
I have install xiki from rubygems.org repository and there are not xsh file there.
```
.
.
.
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Specs/menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Specs/run_spec_in_place-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Specs/enter_as_rspec-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Projects/
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Projects/cdesc-Projects.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Projects/after_menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Projects/menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Projects/before_menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Projects/default_project-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Projects/default-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Gems/
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Gems/cdesc-Gems.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Gems/readme-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Gems/uninstall-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Gems/menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Gems/environment-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Gems/source-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Gems/list-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Gems/gem_dir-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/maybe_code_tree_root-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/paramify-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/cdesc-CodeTree.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/menus-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/add_menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/layout_menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/quote_search_option-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/do_kill_indented-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/escape-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/determine_code_from_path-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/remove_slashes-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/draw_exception-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/extract_class-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/no_search_option-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/tree_search_option-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/run-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/definite_code_tree_root-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/kill_rest-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/handles%3f-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/kill_siblings-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/definite_dir_tree_root-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/extract_method-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/as_indented-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/returned_to_s-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/bulletize-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/CodeTree/launch-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/WebInterface/
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/WebInterface/cdesc-WebInterface.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/WebInterface/menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Dom/
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Dom/tidy-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Dom/dom-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Dom/search-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Dom/cdesc-Dom.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Dom/styles-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Dom/menu-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Dom/menu_after-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Dom/menu_before-c.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Pre/
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Pre/cdesc-Pre.ri
usr/lib64/ruby/gems/2.2.0/doc/xiki-0.6.5/ri/Pre/menu-c.ri
usr/doc/
usr/doc/rubygem-xiki-0.6.5/
usr/doc/rubygem-xiki-0.6.5/rubygem-xiki.SlackBuild
usr/bin/
usr/bin/xiki
```
